services:
  postgres_dev:
    image: postgres:15
    env_file: .env.dev
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}_dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 5433:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - pgnet
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin_dev:
    image: dpage/pgadmin4
    env_file:
      - .env.dev
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}_dev
    restart: unless-stopped
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - 4243:80
    depends_on:
      postgres_dev:
        condition: service_healthy
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
      - /tmp:/tmp
    networks:
      - pgnet

volumes:
  postgres_data_dev:
  pgadmin_data_dev:

networks:
  pgnet:
    external: true
